// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package user

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/rostis232/golangjunior/view/layout"
)

func Library() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!-- Page Heading --> <h1 class=\"h3 mb-2 text-gray-800\">Бібліотека</h1><p class=\"mb-4\">Тут відображаються всі наявні в бібліотеці матеріали</p><div class=\"card shadow mb-4\"><div class=\"card-body\"><div class=\"table-responsive\"><table class=\"table table-bordered\" id=\"dataTable\" width=\"100%\" cellspacing=\"0\"><thead><tr><th>ID</th><th>Назва</th><th>Тип</th><th>Складність</th><th>Мова</th><th>Оцінка</th><th>Докладніше</th></tr></thead><tfoot><tr><th>ID</th><th>Назва</th><th>Тип</th><th>Складність</th><th>Мова</th><th>Оцінка</th><th>Докладніше</th></tr></tfoot><tbody><tr><td>1</td><td>A Tour Of Go</td><td>Інтерактивний курс</td><td>Початкова</td><td>Українська</td><td>5 з 5</td><td><a href=\"\" class=\"btn btn-info btn-icon-split btn-sm\"><span class=\"icon text-white-50\"><i class=\"fas fa-arrow-right\"></i></span> <span class=\"text\">Докладніше</span></a></td></tr></tbody></table></div></div></div><script src=\"/static/vendor/datatables/jquery.dataTables.min.js\"></script> <script src=\"/static/vendor/datatables/dataTables.bootstrap4.min.js\"></script> <script src=\"/static/js/demo/datatables-demo.js\"></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layout.Base("Show").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
